# NumPy - Numerical Python Library

In [1]:
# import NumPy Library
import numpy as np   #import packages from library

In [18]:
arry = np.array([[1,2,3,4],[5,6,7,8]])
arry

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arry[0][0]

1

In [23]:
#Diminsion of array


print(arry.ndim)
print(arry.shape)
print(arry.data) #memoey location where our data is stored
print(arry.size) #nomber of elements
print(type(arry))

2
(2, 4)
8
<class 'numpy.ndarray'>


# LAB-1 Random Number Generation Using NumPy

In [38]:
from numpy import random
x = random.randint(1000) #to print 3 digit number
x

569

In [39]:
y = random.rand(10)
y

array([0.22066394, 0.6343301 , 0.24162404, 0.38493114, 0.07052753,
       0.67510472, 0.09454552, 0.79134229, 0.86251617, 0.83632595])

In [40]:
x = random.randint(100,size=10)
x

array([65, 38, 20, 98, 95, 42, 89, 98, 24, 70])

In [42]:
x = random.randint(1000,size=(3,3)) #to generate 3*3 matrix
x

array([[381, 822, 471],
       [268, 792, 858],
       [403, 285, 625]])